[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_e_commerce = "5y3FcQs2Ar6kTqpsJpJdHRJih3G9WDtsmkiNX54UtPiq"

[programs.localnet]
solana_e_commerce = "5y3FcQs2Ar6kTqpsJpJdHRJih3G9WDtsmkiNX54UtPiq"

[programs.testnet]
solana_e_commerce = "5y3FcQs2Ar6kTqpsJpJdHRJih3G9WDtsmkiNX54UtPiq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.spec.ts'"
