[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_e_commerce = "5XZ74thixMBX2tQN9P3yLTugUK4YMdRLznDNa2mRdGNT"

[programs.localnet]
solana_e_commerce = "5XZ74thixMBX2tQN9P3yLTugUK4YMdRLznDNa2mRdGNT"

[programs.testnet]
solana_e_commerce = "5XZ74thixMBX2tQN9P3yLTugUK4YMdRLznDNa2mRdGNT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.spec.ts'"
